# Site settings
title: Yun Hao
email: yunhaocs@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  
  baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yunhaocs
github_username:  yunhaolucky

# Build settings
#markdown: kramdown

markdown: redcarpet
